name: clear

on:
  workflow_dispatch:
  

jobs:
  clear:
    runs-on: macOS-latest
    env:
      TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
      TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
    steps:
      - uses: actions/checkout@v2
        name: Checkout
        
      - uses: r-lib/actions/setup-r@v2
        name: Setup R
      
      - uses: r-lib/actions/setup-pandoc@v2
        name: Setup Pandoc
        
      - uses: r-lib/actions/setup-renv@v2
          
      - name: Run bot
        run: Rscript R/clear.R



   
