name: clear

on:
  workflow_dispatch:
  

jobs:
  clear:
    runs-on: windows-latest
    env:
      TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
      TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      RENV_PATHS_CACHE: ~/renv/cache
      RENV_PATHS_ROOT: ~/renv
    steps:
      - uses: actions/checkout@v2
        name: Checkout
        
      - uses: r-lib/actions/setup-r@v1
        name: Setup R
      
        
      - uses: actions/cache@v2
        name: Cache for Linux
        if: startsWith(runner.os, 'Linux')    
        with:
          path: ~/.local/share/renv
          key: ${{ runner.os }}-renv2-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv2-
      
      - uses: actions/cache@v2
        name: Cache for macOS
        if: startsWith(runner.os, 'macOS')
        with:
          path: ~/Library/Application Support/renv
          key: ${{ runner.os }}-renv2-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv2-
      
      - uses: actions/cache@v2
        name: Cache for Windows
        if: startsWith(runner.os, 'Windows')  
        with:
          path: ~/renv 
          key: ${{ runner.os }}-renv2-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv2-
            
      - name: Restore packages
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()
          renv::diagnostics()
          
            
      - name: Run bot
        run: Rscript R/clear.R



   
