name: last-tweet

on:
  workflow_dispatch:
  schedule:
    - cron:  '1,21,41 * * * *'
  

jobs:
  last-tweet:
    runs-on: macOS-latest
    env:
      TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
      TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
    steps:
      - uses: actions/checkout@v2
        name: Checkout
        
      - uses: r-lib/actions/setup-r@v1
        name: Setup R
      
      - uses: r-lib/actions/setup-pandoc@master
        name: Setup Pandoc
        
      - uses: actions/cache@v2
        name: Cache for Linux
        if: startsWith(runner.os, 'Linux')    
        with:
          path: ~/.local/share/renv
          key: ${{ runner.os }}-renv2-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv2-
      
      - uses: actions/cache@v2
        name: Cache for macOS
        if: startsWith(runner.os, 'macOS')
        with:
          path: ~/Library/Application Support/renv
          key: ${{ runner.os }}-renv2-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv2-
      
      - uses: actions/cache@v2
        name: Cache for Windows
        if: startsWith(runner.os, 'Windows')  
        with:
          path: ~\AppData\Local\renv
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-
            
      - name: Restore packages
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()
          
            
      - name: Run bot
        run: Rscript R/trigger.R
        
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -A
          git commit -m 'New map created' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
    
   
