name: last-tweet

on:
  workflow_dispatch:
  # schedule:
  #   - cron:  '1,21,41 * * * *'
  

jobs:
  last-tweet:
    runs-on: macOS-latest
    env:
      TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
      TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
    steps:
      - uses: actions/checkout@v2
        
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.1.2'
        
      - uses: r-lib/actions/setup-renv@v2
            
      - name: Run bot
        run: Rscript R/trigger.R
        
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -A
          git commit -m 'New map created' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
    
   
