on:
  workflow_dispatch:
  schedule:
    - cron: '0/15 * * * *'
  
name: tweet-satellite-mask

jobs:
  spain-munic-bot:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
        
      - uses: actions/cache@v2
        if: startsWith(runner.os, 'Linux')    
        with:
          path: ~/.local/share/renv
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-
      
      - uses: actions/cache@v2
        if: startsWith(runner.os, 'macOS')
        with:
          path: ~/Library/Application Support/renv
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-
      
      - uses: actions/cache@v2
        if: startsWith(runner.os, 'Windows')  
        with:
          path: ~\AppData\Local\renv
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-
            

      - name: Run bot
        run: Rscript R/trigger.R
        
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -A
          git commit -m 'Run bot' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
    
   
