name: tweet-satellite-mask

on:
  workflow_dispatch:
  schedule:
    - cron:  '*/15 * * * *'
  

jobs:
  tweet-satellite-mask:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout
        
      - uses: r-lib/actions/setup-r@v1
        name: Setup R
        
      - uses: actions/cache@v2
        name: Cache for Linux
        if: startsWith(runner.os, 'Linux')    
        with:
          path: ~/.local/share/renv
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-
      
      - uses: actions/cache@v2
        name: Cache for macOS
        if: startsWith(runner.os, 'macOS')
        with:
          path: ~/Library/Application Support/renv
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-
      
      - uses: actions/cache@v2
        name: Cache for Windows
        if: startsWith(runner.os, 'Windows')  
        with:
          path: ~\AppData\Local\renv
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-
            

      - name: Run bot
        run: Rscript R/trigger.R
        
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -A
          git commit -m 'Run bot' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
    
   
